/**
 *
 * Standardized action names for audit trail entries.
 * Use these enums instead of string literals for type safety and consistency.
 *
 * @module AuditActions
 */
export enum AuditAction {
  // Payment Actions
  INITIATE_PAYMENT = 'INITIATE_PAYMENT',
  VERIFY_PAYMENT = 'VERIFY_PAYMENT',
  PROCESS_PAYMENT = 'PROCESS_PAYMENT',
  REFUND_PAYMENT = 'REFUND_PAYMENT',
  CANCEL_PAYMENT = 'CANCEL_PAYMENT',
  CREATE_PENALTY_PAYMENT = 'CREATE_PENALTY_PAYMENT',
  PROCESS_PENALTY_PAYMENT = 'PROCESS_PENALTY_PAYMENT',

  // HTTP Actions (for outgoing requests)
  HTTP_GET = 'HTTP_GET',
  HTTP_POST = 'HTTP_POST',
  HTTP_PUT = 'HTTP_PUT',
  HTTP_PATCH = 'HTTP_PATCH',
  HTTP_DELETE = 'HTTP_DELETE',
  HTTP_REQUEST_FAILED = 'HTTP_REQUEST_FAILED',
  HTTP_GET_ERROR = 'HTTP_GET_ERROR',
  HTTP_POST_ERROR = 'HTTP_POST_ERROR',
  HTTP_PUT_ERROR = 'HTTP_PUT_ERROR',
  HTTP_PATCH_ERROR = 'HTTP_PATCH_ERROR',
  HTTP_DELETE_ERROR = 'HTTP_DELETE_ERROR',

  // User Actions
  USER_LOGIN = 'USER_LOGIN',
  USER_LOGOUT = 'USER_LOGOUT',
  USER_REGISTER = 'USER_REGISTER',
  USER_UPDATE = 'USER_UPDATE',
  USER_DELETE = 'USER_DELETE',

  // Resource Actions (generic CRUD)
  CREATE = 'CREATE',
  READ = 'READ',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  LIST = 'LIST',

  // Estate Actions
  CREATE_ESTATE = 'CREATE_ESTATE',
  UPDATE_ESTATE = 'UPDATE_ESTATE',
  DELETE_ESTATE = 'DELETE_ESTATE',
  REMOVE_RESIDENT = 'REMOVE_RESIDENT',
  RESIDENT_LEAVE = 'RESIDENT_LEAVE',
  APPROVE_RESIDENT = 'APPROVE_RESIDENT',
  REJECT_RESIDENT = 'REJECT_RESIDENT',
  SUSPEND_RESIDENT = 'SUSPEND_RESIDENT',

  // Penalty Actions
  CREATE_PENALTY = 'CREATE_PENALTY',
  UPDATE_PENALTY = 'UPDATE_PENALTY',
  DELETE_PENALTY = 'DELETE_PENALTY',
  ASSIGN_PENALTY = 'ASSIGN_PENALTY',

  // Notification Actions
  SEND_EMAIL = 'SEND_EMAIL',
  SEND_SMS = 'SEND_SMS',
  SEND_NOTIFICATION = 'SEND_NOTIFICATION',

  // Webhook Actions
  RECEIVE_WEBHOOK = 'RECEIVE_WEBHOOK',
  PROCESS_WEBHOOK = 'PROCESS_WEBHOOK',

  // Background Job Actions
  PROCESS_BACKGROUND_JOB = 'PROCESS_BACKGROUND_JOB',
  SCHEDULE_TASK = 'SCHEDULE_TASK',
  EXECUTE_TASK = 'EXECUTE_TASK',

  // Security Actions
  TOKEN_BLACKLISTED = 'TOKEN_BLACKLISTED',
  TOKEN_REVOKED = 'TOKEN_REVOKED',
  TOKEN_REFRESHED = 'TOKEN_REFRESHED',
  SUSPICIOUS_ACTIVITY_DETECTED = 'SUSPICIOUS_ACTIVITY_DETECTED',
  IP_VALIDATION_FAILED = 'IP_VALIDATION_FAILED',
  DEVICE_MISMATCH_DETECTED = 'DEVICE_MISMATCH_DETECTED',
  TOKEN_REUSE_DETECTED = 'TOKEN_REUSE_DETECTED',
  RAPID_REFRESH_DETECTED = 'RAPID_REFRESH_DETECTED',
}
