export const MAX_LENGTH_EMAIL_ADDRESS_DB_VALIDATION = 100;
export const MAX_LENGTH_USERNAME_DB_VALIDATION = 24;
export const MIN_LENGTH_NAME_DB_VALIDATION = 2;
export const MAX_LENGTH_NAME_DB_VALIDATION = 30;
export const MIN_LENGTH_PASSWORD_DB_VALIDATION = 8;
export const MAX_LENGTH_PASSWORD_DB_VALIDATION = 32;
